######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 8 00:44:29 2012
######################################################################

TEMPLATE = app
TARGET = Spreadsheet
DEPENDPATH += .
INCLUDEPATH += .

# Directories

FORMS += \
    gotocelldialog.ui

HEADERS += \
    gotocelldialog.h

SOURCES += \
    gotocelldialog.cpp \
    testGoToCellDialog.cpp
